apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: nginxfiles
  namespace: default
spec:
  rules:
    - host: '*.domain.com'
      http:
        paths:
          - path: /.well-known/some-file.txt
            backend:
              serviceName: nginxfiles
              servicePort: http
---
apiVersion: v1
kind: Service
metadata:
  name: nginxfiles
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
  type: NodePort
  selector:
    app: nginxfiles
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxfiles
  labels:
    app: nginxfiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxfiles
  template:
    metadata:
      labels:
        app: nginxfiles
    spec:
      imagePullSecrets:
        - name: tylerorg
      containers:
        - image: org/conainer:tag
          name: nginxfiles
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              memory: 512Mi
              cpu: 200m
            requests:
              memory: 256Mi
              cpu: 200m
